name: carpool
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  bloc: ^8.1.4
  cherry_toast: ^1.10.1
  dartz: ^0.10.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.5
  flutter_localizations:
    sdk: flutter
  flutter_osm_plugin: ^0.70.4
  flutter_screenutil: ^5.9.0
  font_awesome_flutter: ^10.7.0
  get_it: ^7.6.7
  google_nav_bar: ^5.0.6
  http: ^1.2.1
  image_picker: ^1.0.7
  internet_connection_checker: ^1.0.0+1
  introduction_screen: ^3.1.14
  lottie: ^3.1.0
  numberpicker: ^2.1.2
  pin_code_fields: ^8.0.1
  shared_preferences: ^2.2.2
  timeline_tile: ^2.0.0
  url_launcher_windows: ^3.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
   - assets/images/
   - assets/lang/en.json
   - assets/lang/ar.json
   - assets/animations/